/*
 *  tileGtk_Symbols.h
 * --------------------
 *
 * This file is part of the Tile-Gtk package, a Tk/Tile based theme that uses
 * Gtk/GNOME for drawing.
 *
 * Copyright (C) 2004-2012 by:
 * Georgios Petasis, petasis@iit.demokritos.gr,
 * Software and Knowledge Engineering Laboratory,
 * Institute of Informatics and Telecommunications,
 * National Centre for Scientific Research (NCSR) "Demokritos",
 * Aghia Paraskevi, 153 10, Athens, Greece.
 */
/* THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT! */
#ifndef _TILEGTK_SYMBOLS
#define _TILEGTK_SYMBOLS
#include "tcl.h"
#ifdef LOAD_SYMBOLS_WITH_TCL
#else
#include <glib.h>
#endif
#include <gdk/gdk.h>
#include <gtk/gtk.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#ifndef __WIN32__
#include <gdk-pixbuf-xlib/gdk-pixbuf-xlib.h>
#include <gdk/gdkx.h>
#else
#include <gdk/gdkwin32.h>
#endif

#ifdef    TILEGTK_LOAD_GTK_DYNAMICALLY
extern "C" {
  typedef gpointer (*Ptr_g_malloc)(gsize n_bytes);
  extern Ptr_g_malloc TileGtk_g_malloc;
  typedef gpointer (*Ptr_g_malloc0)(gsize n_bytes);
  extern Ptr_g_malloc0 TileGtk_g_malloc0;
}

extern int TileGtk_InitialiseSymbols_glib(Tcl_Interp *interp, Tcl_Obj *file_name);
#define TILEGTK_LAST_SYMBOL_glib TileGtk_g_malloc0

#else  /* TILEGTK_LOAD_GTK_DYNAMICALLY */

#define TileGtk_g_malloc \
                g_malloc
#define TileGtk_g_malloc0 \
                g_malloc0
#endif /* TILEGTK_LOAD_GTK_DYNAMICALLY */

#endif /* _TILEGTK_SYMBOLS */
